[package]
name = "tx-fee-bumper"
version = "0.1.0"
authors = ["Tomasz DrwiÄ™ga <tomusdrw@gmail.com>"]

[dependencies]
ethcore-transaction = { git = "https://github.com/paritytech/parity-ethereum" }
ethkey = { git = "https://github.com/paritytech/parity-ethereum" }
ethstore = { git = "https://github.com/paritytech/parity-ethereum" }
rlp = "0.4"
rpassword = "3.0"
rustc-hex = "2"
serde_json = "1.0"
