[package]
name = "tx-utils"
version = "0.1.0"
authors = ["Tomasz DrwiÄ™ga <tomusdrw@gmail.com>"]
edition = "2018"

[dependencies]
# TODO move this to separate crate
ethereum-transaction = { git = "https://github.com/tomusdrw/jsonrpc-proxy" }
ethsign = "0.7"
rlp = "0.4"
rpassword = "5.0"
rustc-hex = "2"
serde_json = "1.0"
structopt = "0.3"
